name: Scandalorian Discovery Build

on:
  push:
    branches:
      - main

jobs:
  discovery-engine-build-arm:
    runs-on: ubuntu-latest
    name: Build arm version of discovery-engine
    steps:
      - uses: actions/checkout@v2
      - name: Docker Login
        run: docker login --username=${{ secrets.DOCKER_USERNAME }} --password=${{ secrets.DOCKER_PASSWORD }}
      - name: Build Arm
        run: DOCKER_BUILDKIT=1 docker build -t charlesdburton/scandalorian-discovery-engine:arm --target=arm --file=./Dockerfile .
      - name: Push Image
        run: docker push charlesdburton/scandalorian-discovery-engine:arm
  discovery-engine-build-arm64:
    runs-on: ubuntu-latest
    name: Build arm64 version of discovery-engine
    steps:
      - uses: actions/checkout@v2
      - name: Docker Login
        run: docker login --username=${{ secrets.DOCKER_USERNAME }} --password=${{ secrets.DOCKER_PASSWORD }}
      - name: Build Arm64
        run: DOCKER_BUILDKIT=1 docker build -t charlesdburton/scandalorian-discovery-engine:arm64 --target=arm64 --file=./Dockerfile .
      - name: Push Image
        run: docker push charlesdburton/scandalorian-discovery-engine:arm64
  discovery-engine-build-amd64:
    runs-on: ubuntu-latest
    name: Build amd64 version of discovery-engine
    steps:
      - uses: actions/checkout@v2
      - name: Docker Login
        run: docker login --username=${{ secrets.DOCKER_USERNAME }} --password=${{ secrets.DOCKER_PASSWORD }}
      - name: Build AMD64
        run: DOCKER_BUILDKIT=1 docker build -t charlesdburton/scandalorian-discovery-engine:amd64 --target=amd64 --file=./Dockerfile .
      - name: Push Image
        run: docker push charlesdburton/scandalorian-discovery-engine:amd64
  discovery-engine-build-manifest:
    runs-on: ubuntu-latest
    name: Collect manifest and push discovery-engine
    needs: ["discovery-engine-build-arm", "discovery-engine-build-arm64", "discovery-engine-build-amd64"]
    steps:
      - uses: actions/checkout@v2

      - name: Docker Login
        run: docker login --username=${{ secrets.DOCKER_USERNAME }} --password=${{ secrets.DOCKER_PASSWORD }}
      - name: Build Manifest
        run: |
          DOCKER_CLI_EXPERIMENTAL=enabled docker manifest create charlesdburton/scandalorian-discovery-engine:${{ github.sha }} \
          charlesdburton/scandalorian-discovery-engine:amd64 \
          charlesdburton/scandalorian-discovery-engine:arm \
          charlesdburton/scandalorian-discovery-engine:arm64 
      - name: Annotate Arm
        run: DOCKER_CLI_EXPERIMENTAL=enabled docker manifest annotate --arch arm charlesdburton/scandalorian-discovery-engine:${{ github.sha }} charlesdburton/scandalorian-discovery-engine:arm
      - name: Annotate Arm64
        run: DOCKER_CLI_EXPERIMENTAL=enabled docker manifest annotate --arch arm64 charlesdburton/scandalorian-discovery-engine:${{ github.sha }} charlesdburton/scandalorian-discovery-engine:arm64
      - name: Annotate AMD64
        run: DOCKER_CLI_EXPERIMENTAL=enabled docker manifest annotate --arch amd64 charlesdburton/scandalorian-discovery-engine:${{ github.sha }} charlesdburton/scandalorian-discovery-engine:amd64
      - name: Push Manifest
        run: DOCKER_CLI_EXPERIMENTAL=enabled docker manifest push charlesdburton/scandalorian-discovery-engine:${{ github.sha }}

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: ["discovery-engine-build-manifest"]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          repository: 'charles-d-burton/scandalorian'
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
          fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
          ref: 'master'


      - name: Setup Kustomize
        uses: imranismail/setup-kustomize@v1
        with:
          kustomize-version: "3.9.1"

      - name: Edit Kustomize
        run: |
          cd argocd
          kustomize edit set image charlesdburton/scandalorian-ingest:latest=charlesdburton/scandalorian-discovery-engines:${{ github.sha }}
          cat kustomization.yaml

      - name: Commit Files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "Github Actions"
          git commit -a -m "Set Kustomization Docker Tag"
      
      - name: Push Changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.TOKEN }}
          branch: 'master'
          repository: 'charles-d-burton/scandalorian'

